using System.Text;
using Spectre.Console;
using Spectre.Console.Cli;
using Aetheris.Core.Vault;

namespace Aetheris.Cli.Commands;

public class EnvExportCommand : BaseCommand
{
    public class Settings : BaseCommand.Settings
    {
        [CommandOption("--to <PATH>")]
        public string? OutputPath { get; set; }
        
        [CommandOption("--only <PREFIXES>")]
        public string[]? OnlyPrefixes { get; set; }
        
        [CommandOption("--secure")]
        public bool Secure { get; set; }
        
        [CommandOption("--overwrite")]
        public bool Overwrite { get; set; }
    }
    
    public EnvExportCommand(Settings settings) : base(settings) { }
    
    public override async Task<int> ExecuteAsync(CommandContext context)
    {
        var settings = (Settings)CommandSettings;
        var masterPassword = ReadMasterPassword(confirm: false);
        
        try
        {
            using var store = GetVaultStore(masterPassword);
            
            var outputPath = settings.OutputPath ?? ".env";
            
            if (File.Exists(outputPath) && !settings.Overwrite)
            {
                AnsiConsole.MarkupLine($"[red]Output file '{outputPath}' already exists. Use --overwrite to replace it.[/]");
                return 1;
            }
            
            // Collect API key items
            var apiKeyItems = store.Items.Where(i => i.Type == ItemType.ApiKey).ToList();
            
            // Filter by prefixes if specified
            if (settings.OnlyPrefixes != null && settings.OnlyPrefixes.Length > 0)
            {
                apiKeyItems = apiKeyItems.Where(i => 
                    settings.OnlyPrefixes.Any(prefix => 
                        i.Title.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) ||
                        i.Tags.Contains(prefix, StringComparer.OrdinalIgnoreCase))).ToList();
            }
            
            if (apiKeyItems.Count == 0)
            {
                AnsiConsole.MarkupLine("[yellow]No API key items found to export[/]");
                return 0;
            }
            
            var sb = new StringBuilder();
            
            // Add header
            sb.AppendLine("# Aetheris Environment Export");
            sb.AppendLine("# Generated by: aeth env-export");
            sb.AppendLine("# Date: " + DateTimeOffset.UtcNow.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine("# WARNING: This file contains sensitive information!");
            sb.AppendLine("# Keep it secure and never commit to version control.");
            sb.AppendLine();
            
            // Add each API key as environment variable
            foreach (var item in apiKeyItems)
            {
                var payload = item.Payload<ApiKeyPayload>();
                var envName = ConvertToEnvName(item.Title);
                
                sb.AppendLine($"{envName}={payload.Key}");
            }
            
            // Write to file
            await File.WriteAllTextAsync(outputPath, sb.ToString());
            
            // Set permissions if requested
            if (settings.Secure && System.OperatingSystem.IsLinux())
            {
                try
                {
                    // Set file permissions to 0600 (owner read/write only)
                    var fileInfo = new System.IO.FileInfo(outputPath);
                    fileInfo.SetUnixFileMode(System.IO.UnixFileMode.UserRead | System.IO.UnixFileMode.UserWrite);
                    AnsiConsole.MarkupLine("[green]✓ File permissions set to 0600[/]");
                }
                catch
                {
                    AnsiConsole.MarkupLine("[yellow]Warning: Could not set file permissions[/]");
                }
            }
            
            if (CommandSettings.JsonOutput)
            {
                OutputJson(new
                {
                    success = true,
                    outputPath,
                    exportedCount = apiKeyItems.Count,
                    secure = settings.Secure
                });
            }
            else
            {
                AnsiConsole.MarkupLine($"[green]✓ exported {apiKeyItems.Count} API key(s) to '{outputPath}'[/]");
                if (settings.Secure)
                {
                    AnsiConsole.MarkupLine("[dim]File permissions: 0600 (owner read/write only)[/]");
                }
            }
            
            return 0;
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[red]Failed to export environment: {ex.Message}[/]");
            return 1;
        }
    }
    
    private static string ConvertToEnvName(string title)
    {
        // Convert title to environment variable name format
        // Replace spaces and special characters with underscores
        var sb = new StringBuilder();
        foreach (var c in title)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(char.ToUpperInvariant(c));
            }
            else if (c == ' ' || c == '-' || c == '_' || c == '.')
            {
                sb.Append('_');
            }
        }
        
        // Remove leading/trailing underscores
        var result = sb.ToString().Trim('_');
        
        // Ensure it starts with a letter
        if (result.Length > 0 && !char.IsLetter(result[0]))
        {
            result = "_" + result;
        }
        
        return result;
    }
}